/**
 * Builds the source-map module read by the inline `<cts-source-viewer>`.
 *
 * The site demo lets visitors expand each playground to see the actual TS
 * source that powers it. We don't fetch those files at runtime (different
 * deploys serve different assets), so we bake the raw files into a generated
 * module that the source-viewer imports.
 *
 * The generator writes into `.tmp/site/source-viewer/sources.generated.ts`
 * (post-`inlineSources`) so the committed `demos/.../sources.generated.ts`
 * can stay an empty stub and never thrash git diffs.
 */
const path = require('path');
const { readFileSync, writeFileSync, existsSync, mkdirSync } = require('fs');

// slug → list of files that show up as tabs inside the viewer.
// Order matters: the first entry is the default tab.
const ENTRIES = [
  {
    slug: 'counter',
    folder: 'demos/counter',
    files: ['counter.element.ts'],
  },
  {
    slug: 'todo-dashboard',
    folder: 'demos/todo-dashboard',
    files: [
      'todo-dashboard.element.ts',
      'todo-stats.element.ts',
      'todo-filters.element.ts',
      'todo-item.element.ts',
    ],
  },
];

const OUTPUT_REL = path.join('site', 'source-viewer', 'sources.generated.ts');

function buildSourcesMap() {
  const map = {};
  for (const entry of ENTRIES) {
    map[entry.slug] = entry.files
      .map((name) => {
        const fullPath = path.join(entry.folder, name);
        if (!existsSync(fullPath)) {
          console.warn(`generate-sources: missing ${fullPath}; skipping.`);
          return null;
        }
        return { name, source: readFileSync(fullPath, 'utf-8') };
      })
      .filter(Boolean);
  }
  return map;
}

function renderModule(map) {
  // JSON is a strict subset of TS object literals, so we can stringify the
  // whole map and slot it straight into a `const`. Forces UNIX newlines so
  // the output stays stable across platforms.
  const body = JSON.stringify(map, null, 2);
  return [
    '// AUTO-GENERATED by tools/generate-sources.js — do not edit by hand.',
    '// Regenerated on every build/start so the live viewer always shows',
    '// the source that ships with the bundle.',
    '',
    'export interface SourceFile {',
    '  name: string;',
    '  source: string;',
    '}',
    '',
    `export const SOURCES: Record<string, SourceFile[]> = ${body};`,
    '',
  ].join('\n');
}

/**
 * @param {string} destRoot — typically `.tmp` (the staged copy of demos/).
 */
function generateSources(destRoot) {
  const map = buildSourcesMap();
  const outPath = path.join(destRoot, OUTPUT_REL);
  const outDir = path.dirname(outPath);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }
  writeFileSync(outPath, renderModule(map));
}

module.exports = { generateSources, ENTRIES };
