/**
 * Builds the source map consumed by <cts-source-viewer>.
 */
const path = require('path');
const { readFileSync, writeFileSync, existsSync, mkdirSync } = require('fs');

// First file is the default tab.
const ENTRIES = [
  {
    slug: 'counter',
    folder: 'demos/counter',
    files: ['counter.element.ts'],
  },
  {
    slug: 'todo-dashboard',
    folder: 'demos/todo-dashboard',
    files: [
      'todo-dashboard.element.ts',
      'todo-stats.element.ts',
      'todo-filters.element.ts',
      'todo-item.element.ts',
    ],
  },
];

const OUTPUT_REL = path.join('site', 'source-viewer', 'sources.generated.ts');

function buildSourcesMap() {
  const map = {};
  for (const entry of ENTRIES) {
    map[entry.slug] = entry.files
      .map((name) => {
        const fullPath = path.join(entry.folder, name);
        if (!existsSync(fullPath)) {
          console.warn(`generate-sources: missing ${fullPath}; skipping.`);
          return null;
        }
        return { name, source: readFileSync(fullPath, 'utf-8') };
      })
      .filter(Boolean);
  }
  return map;
}

function renderModule(map) {
  // JSON can be embedded directly as a TS object literal.
  const body = JSON.stringify(map, null, 2);
  return [
    '// AUTO-GENERATED by tools/generate-sources.js — do not edit by hand.',
    '// Regenerated on every build/start so the live viewer always shows',
    '// the source that ships with the bundle.',
    '',
    'export interface SourceFile {',
    '  name: string;',
    '  source: string;',
    '}',
    '',
    `export const SOURCES: Record<string, SourceFile[]> = ${body};`,
    '',
  ].join('\n');
}

/**
 * @param {string} destRoot Usually `.tmp`.
 */
function generateSources(destRoot) {
  const map = buildSourcesMap();
  const outPath = path.join(destRoot, OUTPUT_REL);
  const outDir = path.dirname(outPath);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }
  writeFileSync(outPath, renderModule(map));
}

module.exports = { generateSources, ENTRIES };
